from __future__ import annotations

import json
import math
from pathlib import Path

from .executor_protocol import ExecutorTaskRequest, ExecutorTaskResult, ExecutorTimelineEvent
from .models import ArtifactItem


def _metric_profile(geometry_family: str | None) -> dict[str, float]:
    profiles = {
        "DARPA SUBOFF": {
            "drag_coefficient": 0.00348,
            "drag_newtons": 1248.0,
            "pressure_peak_kpa": 21.6,
            "wake_uniformity": 0.87,
        },
        "Joubert BB2": {
            "drag_coefficient": 0.00362,
            "drag_newtons": 1311.0,
            "pressure_peak_kpa": 22.9,
            "wake_uniformity": 0.84,
        },
        "Type 209": {
            "drag_coefficient": 0.00395,
            "drag_newtons": 1388.0,
            "pressure_peak_kpa": 24.7,
            "wake_uniformity": 0.81,
        },
    }
    return profiles.get(
        geometry_family or "",
        {
            "drag_coefficient": 0.00412,
            "drag_newtons": 1420.0,
            "pressure_peak_kpa": 25.1,
            "wake_uniformity": 0.79,
        },
    )


def _build_svg(title: str, color: str, values: list[float]) -> str:
    width = 680
    height = 260
    base_x = 60
    base_y = 210
    spacing = 560 / max(len(values) - 1, 1)
    max_value = max(values)
    min_value = min(values)
    span = max(max_value - min_value, 1e-6)
    points: list[str] = []

    for index, value in enumerate(values):
        x = base_x + index * spacing
        normalized = (value - min_value) / span
        y = base_y - normalized * 120
        points.append(f"{x:.1f},{y:.1f}")

    circles = []
    for point in points:
        x, y = point.split(",")
        circles.append(f'<circle cx="{x}" cy="{y}" r="5" fill="{color}" />')

    grid_lines = "\n".join(
        f'<line x1="{base_x}" y1="{y}" x2="{base_x + 560}" y2="{y}" stroke="rgba(255,255,255,0.08)" />'
        for y in (90, 130, 170, 210)
    )

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="#071927" />
      <stop offset="100%" stop-color="#10334a" />
    </linearGradient>
  </defs>
  <rect width="{width}" height="{height}" rx="24" fill="url(#bg)" />
  <text x="40" y="44" fill="#f8fafc" font-size="24" font-family="Segoe UI, sans-serif">{title}</text>
  <text x="40" y="70" fill="#93c5fd" font-size="12" font-family="Segoe UI, sans-serif">Generated by the claude-executor stub service</text>
  {grid_lines}
  <line x1="{base_x}" y1="{base_y}" x2="{base_x + 560}" y2="{base_y}" stroke="rgba(255,255,255,0.35)" />
  <polyline fill="none" stroke="{color}" stroke-width="4" points="{' '.join(points)}" />
  {''.join(circles)}
</svg>
"""


def _artifact_url(run_id: str, relative_path: str) -> str:
    return f"/api/runs/{run_id}/artifacts/{relative_path}"


def run_stub_executor(request: ExecutorTaskRequest) -> ExecutorTaskResult:
    run_path = Path(request.run_directory)
    for relative in (
        "execution/claude_executor",
        "execution/logs",
        "postprocess/images",
        "postprocess/tables",
        "report",
    ):
        (run_path / relative).mkdir(parents=True, exist_ok=True)

    request_path = run_path / "execution" / "claude_executor" / "request.json"
    request_path.write_text(
        json.dumps(request.model_dump(mode="json"), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    metrics = _metric_profile(request.context.geometry_family)
    pressure_values = [
        metrics["pressure_peak_kpa"] * (0.72 + math.sin(index / 2.4) * 0.12 + index * 0.015)
        for index in range(10)
    ]
    wake_values = [
        metrics["wake_uniformity"] * (0.88 + math.cos(index / 3.1) * 0.08)
        for index in range(10)
    ]

    log_path = run_path / "execution" / "logs" / "run.log"
    log_path.write_text(
        "\n".join(
            [
                "[claude-executor] Accepted structured stage request.",
                f"[claude-executor] Goal: {request.goal}",
                f"[claude-executor] Allowed tools: {', '.join(request.allowed_tools) or 'none'}",
                "[claude-executor] Stub mode: simulating controlled multi-step execution.",
                "[geometry] Geometry inspection passed for the selected benchmark family.",
                "[solver] Delegating to deterministic demo output generator.",
                "[postprocess] Exporting images, metrics, and markdown report.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    (run_path / "postprocess" / "images" / "pressure_distribution.svg").write_text(
        _build_svg("Pressure Distribution", "#38bdf8", pressure_values),
        encoding="utf-8",
    )
    (run_path / "postprocess" / "images" / "wake_field.svg").write_text(
        _build_svg("Wake Field Slice", "#f59e0b", wake_values),
        encoding="utf-8",
    )
    (run_path / "postprocess" / "tables" / "drag.csv").write_text(
        "\n".join(
            [
                "metric,value,unit",
                f"drag_coefficient,{metrics['drag_coefficient']:.5f},-",
                f"drag_newtons,{metrics['drag_newtons']:.1f},N",
                f"pressure_peak_kpa,{metrics['pressure_peak_kpa']:.2f},kPa",
                f"wake_uniformity,{metrics['wake_uniformity']:.3f},-",
            ]
        ),
        encoding="utf-8",
    )
    (run_path / "postprocess" / "result.json").write_text(
        json.dumps(
            {
                "run_id": request.run_id,
                "task_type": request.context.task_type,
                "geometry_family": request.context.geometry_family,
                "selected_case_id": request.context.selected_case_id,
                "allowed_tools": request.allowed_tools,
                "metrics": metrics,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    report_markdown = "\n".join(
        [
            f"# Claude Executor Report: {request.run_id}",
            "",
            "## Stage Goal",
            request.goal,
            "",
            "## Task Context",
            f"- Description: {request.context.task_description}",
            f"- Task type: `{request.context.task_type}`",
            f"- Geometry family: {request.context.geometry_family or 'N/A'}",
            f"- Selected case: {request.context.selected_case_title or 'N/A'}",
            "",
            "## Tool Envelope",
            *[f"- `{tool}`" for tool in request.allowed_tools],
            "",
            "## Result Summary",
            "- The executor used a deterministic stub path to simulate controlled stage execution.",
            "- Request and response manifests were written into the run directory.",
            "- Generated artifacts follow the same output contract expected by the UI.",
        ]
    ).strip() + "\n"
    (run_path / "report" / "final_report.md").write_text(report_markdown, encoding="utf-8")

    artifacts = [
        ArtifactItem(
            label="Execution Log",
            category="log",
            relative_path="execution/logs/run.log",
            mime_type="text/plain",
            url=_artifact_url(request.run_id, "execution/logs/run.log"),
        ),
        ArtifactItem(
            label="Pressure Distribution",
            category="image",
            relative_path="postprocess/images/pressure_distribution.svg",
            mime_type="image/svg+xml",
            url=_artifact_url(request.run_id, "postprocess/images/pressure_distribution.svg"),
        ),
        ArtifactItem(
            label="Wake Field",
            category="image",
            relative_path="postprocess/images/wake_field.svg",
            mime_type="image/svg+xml",
            url=_artifact_url(request.run_id, "postprocess/images/wake_field.svg"),
        ),
        ArtifactItem(
            label="Drag Metrics",
            category="table",
            relative_path="postprocess/tables/drag.csv",
            mime_type="text/csv",
            url=_artifact_url(request.run_id, "postprocess/tables/drag.csv"),
        ),
        ArtifactItem(
            label="Structured Result",
            category="json",
            relative_path="postprocess/result.json",
            mime_type="application/json",
            url=_artifact_url(request.run_id, "postprocess/result.json"),
        ),
        ArtifactItem(
            label="Final Report",
            category="report",
            relative_path="report/final_report.md",
            mime_type="text/markdown",
            url=_artifact_url(request.run_id, "report/final_report.md"),
        ),
    ]
    (run_path / "report" / "artifact_manifest.json").write_text(
        json.dumps(
            [artifact.model_dump(mode="json") for artifact in artifacts],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    result = ExecutorTaskResult(
        job_id=request.job_id,
        run_id=request.run_id,
        status="completed",
        summary="claude-executor stub completed the stage and returned structured artifacts.",
        executor_name="claude-executor-stub",
        used_tools=request.allowed_tools,
        metrics=metrics,
        timeline=[
            ExecutorTimelineEvent(
                stage="execution",
                message="claude-executor accepted the structured task and built a tool plan.",
                status="running",
            ),
            ExecutorTimelineEvent(
                stage="postprocess",
                message="claude-executor wrote structured outputs and benchmark-style metrics.",
                status="running",
            ),
            ExecutorTimelineEvent(
                stage="report",
                message="claude-executor generated the stage report and artifact manifest.",
                status="ok",
            ),
        ],
        artifacts=artifacts,
        report_markdown=report_markdown,
    )

    response_path = run_path / "execution" / "claude_executor" / "response.json"
    response_path.write_text(
        json.dumps(result.model_dump(mode="json"), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return result
