from __future__ import annotations

import json
import math
import threading
import time
from pathlib import Path

from ..config import get_settings
from ..models import ArtifactItem, RunStatus
from ..store import RunStore


class MockExecutionEngine:
    engine_name = "mock"

    def __init__(self, store: RunStore) -> None:
        self.store = store
        self.settings = get_settings()

    def launch(self, run_id: str) -> None:
        thread = threading.Thread(target=self.run_pipeline, args=(run_id,), daemon=True)
        thread.start()

    def _sleep(self) -> None:
        if self.settings.execution_delay_seconds > 0:
            time.sleep(self.settings.execution_delay_seconds)

    def _metric_profile(self, geometry_family: str) -> dict[str, float]:
        profiles = {
            "DARPA SUBOFF": {
                "drag_coefficient": 0.00348,
                "drag_newtons": 1248.0,
                "pressure_peak_kpa": 21.6,
                "wake_uniformity": 0.87,
            },
            "Joubert BB2": {
                "drag_coefficient": 0.00362,
                "drag_newtons": 1311.0,
                "pressure_peak_kpa": 22.9,
                "wake_uniformity": 0.84,
            },
            "Type 209": {
                "drag_coefficient": 0.00395,
                "drag_newtons": 1388.0,
                "pressure_peak_kpa": 24.7,
                "wake_uniformity": 0.81,
            },
        }
        return profiles.get(
            geometry_family,
            {
                "drag_coefficient": 0.00412,
                "drag_newtons": 1420.0,
                "pressure_peak_kpa": 25.1,
                "wake_uniformity": 0.79,
            },
        )

    def _write_log(self, run_path: Path, message: str) -> None:
        with (run_path / "execution" / "logs" / "run.log").open("a", encoding="utf-8") as handle:
            handle.write(message.rstrip() + "\n")

    def _build_svg(self, title: str, color: str, values: list[float]) -> str:
        width = 680
        height = 260
        base_x = 60
        base_y = 210
        spacing = 560 / max(len(values) - 1, 1)
        max_value = max(values)
        min_value = min(values)
        span = max(max_value - min_value, 1e-6)
        points: list[str] = []

        for index, value in enumerate(values):
            x = base_x + index * spacing
            normalized = (value - min_value) / span
            y = base_y - normalized * 120
            points.append(f"{x:.1f},{y:.1f}")

        circles = []
        for point in points:
            x, y = point.split(",")
            circles.append(f'<circle cx="{x}" cy="{y}" r="5" fill="{color}" />')

        grid_lines = "\n".join(
            f'<line x1="{base_x}" y1="{y}" x2="{base_x + 560}" y2="{y}" stroke="rgba(255,255,255,0.08)" />'
            for y in (90, 130, 170, 210)
        )

        return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="#071927" />
      <stop offset="100%" stop-color="#10334a" />
    </linearGradient>
  </defs>
  <rect width="{width}" height="{height}" rx="24" fill="url(#bg)" />
  <text x="40" y="44" fill="#f8fafc" font-size="24" font-family="Segoe UI, sans-serif">{title}</text>
  <text x="40" y="70" fill="#93c5fd" font-size="12" font-family="Segoe UI, sans-serif">Generated by the mock submarine workflow executor</text>
  {grid_lines}
  <line x1="{base_x}" y1="{base_y}" x2="{base_x + 560}" y2="{base_y}" stroke="rgba(255,255,255,0.35)" />
  <polyline fill="none" stroke="{color}" stroke-width="4" points="{' '.join(points)}" />
  {''.join(circles)}
</svg>
"""

    def _artifact_url(self, run_id: str, relative_path: str) -> str:
        return f"/api/runs/{run_id}/artifacts/{relative_path}"

    def run_pipeline(self, run_id: str):
        run = self.store.get_run(run_id)
        if run.status not in {RunStatus.RUNNING, RunStatus.AWAITING_CONFIRMATION}:
            raise RuntimeError(f"Run {run_id} is not ready for execution.")

        run_path = Path(run.run_directory)
        selected_family = (
            run.selected_case.geometry_family
            if run.selected_case is not None
            else (run.request.geometry_family_hint or "Unknown")
        )
        metrics = self._metric_profile(selected_family)

        self.store.append_timeline(run_id, "execution", "Launch mock template execution.", "running")
        self.store.set_stage(run_id, "execution", "Running")
        self._write_log(run_path, "[executor] Accepted execution request.")
        self._write_log(run_path, f"[geometry] Family mapped to {selected_family}.")
        self._sleep()

        self._write_log(run_path, "[mesh] Surface cleanup completed. Reference mesh selected.")
        self._write_log(run_path, "[solver] Simulating OpenFOAM steady-state RANS execution.")
        self._sleep()

        self.store.append_timeline(run_id, "postprocess", "Solver finished, exporting artifacts.", "running")
        self.store.set_stage(run_id, "postprocess", "Postprocessing")

        pressure_values = [
            metrics["pressure_peak_kpa"] * (0.72 + math.sin(index / 2.4) * 0.12 + index * 0.015)
            for index in range(10)
        ]
        wake_values = [
            metrics["wake_uniformity"] * (0.88 + math.cos(index / 3.1) * 0.08)
            for index in range(10)
        ]

        (run_path / "postprocess" / "images" / "pressure_distribution.svg").write_text(
            self._build_svg("Pressure Distribution", "#38bdf8", pressure_values),
            encoding="utf-8",
        )
        (run_path / "postprocess" / "images" / "wake_field.svg").write_text(
            self._build_svg("Wake Field Slice", "#f59e0b", wake_values),
            encoding="utf-8",
        )
        (run_path / "postprocess" / "tables" / "drag.csv").write_text(
            "\n".join(
                [
                    "metric,value,unit",
                    f"drag_coefficient,{metrics['drag_coefficient']:.5f},-",
                    f"drag_newtons,{metrics['drag_newtons']:.1f},N",
                    f"pressure_peak_kpa,{metrics['pressure_peak_kpa']:.2f},kPa",
                    f"wake_uniformity,{metrics['wake_uniformity']:.3f},-",
                ]
            ),
            encoding="utf-8",
        )
        (run_path / "postprocess" / "result.json").write_text(
            json.dumps(
                {
                    "run_id": run_id,
                    "geometry_family": selected_family,
                    "task_type": run.request.task_type,
                    "metrics": metrics,
                    "selected_case_id": run.selected_case.case_id if run.selected_case else None,
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        self._write_log(run_path, "[postprocess] Exported pressure_distribution.svg, wake_field.svg, drag.csv.")
        self._sleep()

        self.store.append_timeline(run_id, "report", "Generate final report.", "running")
        self.store.set_stage(run_id, "report", "Reporting")

        report_markdown = "\n".join(
            [
                f"# Run Report: {run_id}",
                "",
                "## Task",
                f"- Description: {run.request.task_description}",
                f"- Task type: `{run.request.task_type}`",
                f"- Geometry hint: {run.request.geometry_family_hint or 'N/A'}",
                "",
                "## Selected Case",
                f"- {run.selected_case.title if run.selected_case else 'N/A'}",
                f"- Reuse role: {run.selected_case.reuse_role if run.selected_case else 'N/A'}",
                "",
                "## Metrics",
                *[f"- {key}: {value}" for key, value in metrics.items()],
                "",
                "## Why this result is trustworthy",
                "- The workflow is case-guided rather than black-box execution.",
                "- Intermediate artifacts and logs are stored in the run directory.",
                "- The report keeps the selected case, assumptions, and generated evidence together.",
            ]
        ).strip() + "\n"
        (run_path / "report" / "final_report.md").write_text(report_markdown, encoding="utf-8")

        artifacts = [
            ArtifactItem(
                label="Execution Log",
                category="log",
                relative_path="execution/logs/run.log",
                mime_type="text/plain",
                url=self._artifact_url(run_id, "execution/logs/run.log"),
            ),
            ArtifactItem(
                label="Pressure Distribution",
                category="image",
                relative_path="postprocess/images/pressure_distribution.svg",
                mime_type="image/svg+xml",
                url=self._artifact_url(run_id, "postprocess/images/pressure_distribution.svg"),
            ),
            ArtifactItem(
                label="Wake Field",
                category="image",
                relative_path="postprocess/images/wake_field.svg",
                mime_type="image/svg+xml",
                url=self._artifact_url(run_id, "postprocess/images/wake_field.svg"),
            ),
            ArtifactItem(
                label="Drag Metrics",
                category="table",
                relative_path="postprocess/tables/drag.csv",
                mime_type="text/csv",
                url=self._artifact_url(run_id, "postprocess/tables/drag.csv"),
            ),
            ArtifactItem(
                label="Structured Result",
                category="json",
                relative_path="postprocess/result.json",
                mime_type="application/json",
                url=self._artifact_url(run_id, "postprocess/result.json"),
            ),
            ArtifactItem(
                label="Final Report",
                category="report",
                relative_path="report/final_report.md",
                mime_type="text/markdown",
                url=self._artifact_url(run_id, "report/final_report.md"),
            ),
        ]
        (run_path / "report" / "artifact_manifest.json").write_text(
            json.dumps(
                [artifact.model_dump(mode="json") for artifact in artifacts],
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        self._write_log(run_path, "[report] Generated final_report.md and artifact_manifest.json.")
        self.store.append_timeline(run_id, "completed", "Run completed; report and artifacts are ready.", "ok")
        return self.store.complete_run(
            run_id,
            artifacts=artifacts,
            report_markdown=report_markdown,
            metrics=metrics,
        )
